/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testdecode_RSDecoder */

#ifndef _Included_com_example_testdecode_RSDecoder
#define _Included_com_example_testdecode_RSDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testdecode_RSDecoder
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_testdecode_RSDecoder_addInt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_testdecode_RSDecoder
 * Method:    decodeRS
 * Signature: ([I[I)I
 */
JNIEXPORT jint JNICALL Java_com_example_testdecode_RSDecoder_decodeRS
  (JNIEnv *, jobject, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
